force-app/main/default/objects/Health_Insurance_Provider__c/Health_Insurance_Provider__c.object-meta.xml
<CustomObject>
    <description>Represents the various Health Insurance Providers that the clinic works with</description>
    <label>Health Insurance Provider</label>
    <nameField>
        <label>Health Insurance Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Health Insurance Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <description>Object representing a patient at the clinic</description>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of the patient</description>
    <label>Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Birthdate of the patient</description>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>patient&apos;s email</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Patient&apos;s gender</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gender</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Health_Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>Health_Insurance_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the health insurance provider of the patient</description>
    <label>Health Insurance Provider</label>
    <referenceTo>Health_Insurance_Provider__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last name of the patient</description>
    <label>Last Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>phone number of the patient</description>
    <label>Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/globalValueSets/Gender.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <description>Shows the patient gendre</description>
    <masterLabel>Gender</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PatientControllerTests.cls
@IsTest
private class PatientControllerTests {

  @TestSetup
  static void makeData(){
    Health_Insurance_Provider__c testHip = new Health_Insurance_Provider__c(Name= 'Galeno');
    insert testHip;

    Patient__c individualPatient = new Patient__c(
      age__c=18, 
      Date_of_Birth__c= Date.newInstance(1960, 2, 17), 
      email__c= 'patient1@gmail.com', 
      Gender__c= 'Male',
      Health_Insurance_Provider__c = testHip.Id,
      Name= 'John',
      Last_Name__c= 'Smith',
      Phone_Number__c = '341-234-4987'
    );
    insert individualPatient;
  }

  @IsTest
  private static void successfulGetPatientById() {
    //Given
    Patient__c testPatient = [SELECT Id, age__c, Date_of_Birth__c, email__c, Gender__c, Health_Insurance_Provider__c, Name, Last_Name__c, Phone_Number__c
                              FROM Patient__c
                              LIMIT 1];

    //When
    Test.startTest();
      Patient__c resultingPatient = PatientController.getPatientById(testPatient.Id);
    Test.stopTest();

    //Then
    System.assertEquals(testPatient.Id, resultingPatient.Id);
    Assert.isNotNull(resultingPatient);
  }
}